name: Convert proxy-list.txt

on:
  schedule:
    - cron: '0 2 * * *' # 每天UTC时间2点自动运行
  workflow_dispatch: # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download proxy-list.txt
        run: |
          curl -sSL -o proxy-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt

      - name: Convert to Loon format
        run: |
          # 创建目标目录 Rule
          mkdir -p Rule
          # 写入规则头部
          echo '[Rule]' > Rule/Proxy-List.list
          # 读取每一行
          while read -r line; do
            # 忽略空行和注释
            if [[ -n "$line" && ! "$line" =~ ^# ]]; then
              # 处理 "full:" 开头的规则
              if [[ "$line" =~ ^full: ]]; then
                domain="${line#full:}"
                # 写入 DOMAIN 格式
                echo "DOMAIN, $domain" >> Rule/Proxy-List.list
              # 处理类似 "regexp:" 的规则
              elif [[ "$line" =~ ^regexp: ]]; then
                regex="${line#regexp:}"
                # 确保正则表达式格式正确
                echo "URL-REGEX, \"^https?:\/\/(.*\.)?$regex\"" >> Rule/Proxy-List.list
              # 处理一般域名，转换为 "DOMAIN-SUFFIX"
              else
                echo "DOMAIN-SUFFIX, $line" >> Rule/Proxy-List.list
              fi
            fi
          done < proxy-list.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Proxy-List.list on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD
