name: Convert proxy-list.txt

on:
  schedule:
    - cron: '0 2 * * *' # 每天UTC时间2点自动运行
  workflow_dispatch: # 允许手动触发

permissions:
  actions: write
  contents: write  

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: sooyaaabo/Loon
          path: Loon

      - name: Download Global Domain List
        run: |
          curl -O https://raw.githubusercontent.com/Code-Dramatist/Rule_Actions/main/Proxy_Rule/Global_Domain.list
            
      - name: Process and Modify Domain List
        run: |
          # 创建目标目录 Rule
          mkdir -p Loon/Rule
          # 写入规则头部
          echo '# 原始链接：https://raw.githubusercontent.com/Code-Dramatist/Rule_Actions/main/Proxy_Rule/Global_Domain.list' > Loon/Rule/Global_Domain.list
          # 创建一个新的文件来保存修改后的域名
          output_file="Processed_Global_Domain.list"
          > $output_file

          # 读取并处理每一行
          while IFS= read -r line; do
            if [[ "$line" =~ ^\. ]]; then
              # 如果行是以.开头，替换为DOMAIN-SUFFIX
              echo "DOMAIN-SUFFIX,${line:1}" >> $output_file
            else
              # 如果行不是以.开头，添加DOMAIN
              echo "DOMAIN,$line" >> $output_file
            fi
          done < Global_Domain.list

      - name: Commit and push changes
        run: |
          cd Loon
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Global_Domain Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
          
      - name: 清理Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 5
