name: Replace URLs in .plugin files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Replace text in .plugin files
    - name: Replace URLs in .plugin files
      run: |
        # Find all .plugin files in the Loon directory and replace the URL
        find ./Loon -type f -name "*.plugin" | while read plugin_file; do
          echo "Processing file: $plugin_file"
          
          # Replace the old URL with the new one
          sed -i 's|https://kelee.one/Resource/Script/|https://kelee.one/Resource/JavaScript/|g' "$plugin_file"
        done

    # Step 3: Commit the changes if any file was modified
    - name: Commit changes if any
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'git
